name: Deploy to staging
on:
  repository_dispatch:
    types: [deploy-command]

jobs:
  deploy-staging:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SUBSCRIPTION_SECRET }}

    - uses: chrnorm/deployment-action@v1.2.0
      name: Create GitHub deployment
      id: deployment
      with:
        token: ${{github.token }}
        ref: ${{ github.event.client_payload.pull_request.head.sha }}
        environment: staging

    - name: Deploy popular repos
      uses: azure/webapps-deploy@v2
      id: popular-repos-web
      with:
        app-name: 'popular-repos'
        images: '${{ secrets.AZURE_REGISTRY_NAME }}/popular-repos:${{ github.event.client_payload.pull_request.head.sha}}'
        slot-name: staging

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: ${{ steps.popular-repos-web.outputs.webapp-url }}
        state: "success"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    - name: Comment on success
      if: success()
      uses: peter-evans/create-or-update-comment@v1.4.1
      with:
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
        reaction: hooray
        body: |
          Successfully deployed [PR-${{ github.event.client_payload.pull_request.number }}](https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id }}) to [staging](${{ steps.popular-repos-web.outputs.webapp-url }})


    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        state: "failure"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    - name: Comment on failure
      if: failure()
      uses: peter-evans/create-or-update-comment@v1.4.1
      with:
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
        reaction: eyes, confused
        body: |
          Failed to deploy #${{ github.event.client_payload.pull_request.number }} to staging

          See https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id }}
